fig_w, fig_h = 5, 5
empty = 'o'

figures = {
    'S':
    [
        [
            'ooooo',
            'ooooo',
            'ooxxo',
            'oxxoo',
            'ooooo'
        ],
        [
            'ooooo',
            'ooxoo',
            'ooxxo',
            'oooxo',
            'ooooo'
        ]
    ],
    'Z':
    [
        [
            'ooooo',
            'ooooo',
            'oxxoo',
            'ooxxo',
            'ooooo'
        ],
        [
            'ooooo',
            'ooxoo',
            'oxxoo',
            'oxooo',
            'ooooo'
        ]
    ],
    'J':
    [
        [
            'ooooo',
            'oxooo',
            'oxxxo',
            'ooooo',
            'ooooo'
        ],
        [
            'ooooo',
            'ooxxo',
            'ooxoo',
            'ooxoo',
            'ooooo'
        ],
        [
            'ooooo',
            'ooooo',
            'oxxxo',
            'oooxo',
            'ooooo'
        ],
        [
            'ooooo',
            'ooxoo',
            'ooxoo',
            'oxxoo',
            'ooooo'
        ]
    ],
    'L':
    [
        [
            'ooooo',
            'oooxo',
            'oxxxo',
            'ooooo',
            'ooooo'
        ],
        [
            'ooooo',
            'ooxoo',
            'ooxoo',
            'ooxxo',
            'ooooo'
        ],
        [
            'ooooo',
            'ooooo',
            'oxxxo',
            'oxooo',
            'ooooo'
        ],
        [
            'ooooo',
            'oxxoo',
            'ooxoo',
            'ooxoo',
            'ooooo'
        ]
    ],
    'I':
    [
        [
            'ooxoo',
            'ooxoo',
            'ooxoo',
            'ooxoo',
            'ooooo'
        ],
        [
            'ooooo',
            'ooooo',
            'xxxxo',
            'ooooo',
            'ooooo'
        ]
    ],
    'O':
    [
        [
            'ooooo',
            'ooooo',
            'oxxoo',
            'oxxoo',
            'ooooo'
        ]
    ],
    'T':
    [
        [
            'ooooo',
            'ooxoo',
            'oxxxo',
            'ooooo',
            'ooooo'
        ],
        [
            'ooooo',
            'ooxoo',
            'ooxxo',
            'ooxoo',
            'ooooo'
        ],
        [
            'ooooo',
            'ooooo',
            'oxxxo',
            'ooxoo',
            'ooooo'
        ],
        [
            'ooooo',
            'ooxoo',
            'oxxoo',
            'ooxoo',
            'ooooo'
        ]
    ]
}
